# Server 설정
server: 
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MySQL 및 JPA 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbsk?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: bbsk3939
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true